# Define explicitamente que queremos Java e Maven
[phases.setup]
nixPkgs = ["jdk21", "maven"]

# Define o comando de build (usando o wrapper para garantir compatibilidade)
[phases.build]
cmds = ["chmod +x mvnw", "./mvnw clean package -DskipTests"]

# Define como iniciar o servidor
[start]
cmd = "java -jar target/*.jar"